export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: 'breakfast' | 'lunch' | 'snacks' | 'dinner';
  isVeg: boolean;
  available: boolean;
  isCombo?: boolean;
  originalPrice?: number;
  customizations?: string[];
};

export const menuItems: MenuItem[] = [
  // Breakfast
  {
    id: 'b1',
    name: 'Idli Sambar',
    description: '3 soft idlis with sambar and chutney',
    price: 40,
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
    customizations: ['Extra Sambar', 'Extra Chutney', 'Ghee'],
  },
  {
    id: 'b2',
    name: 'Masala Dosa',
    description: 'Crispy dosa with potato masala filling',
    price: 50,
    image: 'https://images.unsplash.com/photo-1694501264904-e1e5a7ab2e37?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
    customizations: ['Extra Masala', 'Ghee Roast', 'Paper Dosa'],
  },
  {
    id: 'b3',
    name: 'Poha',
    description: 'Flattened rice with peanuts and spices',
    price: 30,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
  },
  {
    id: 'b4',
    name: 'Vada Sambar',
    description: '3 crispy vadas with sambar',
    price: 45,
    image: 'https://images.unsplash.com/photo-1626776876729-bab4eda331c0?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
  },
  {
    id: 'b5',
    name: 'Upma',
    description: 'South Indian semolina breakfast with vegetables',
    price: 35,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
  },
  {
    id: 'b6',
    name: 'Aloo Paratha',
    description: 'Stuffed flatbread with spiced potato filling',
    price: 45,
    image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
    customizations: ['Extra Butter', 'Curd'],
  },
  {
    id: 'b7',
    name: 'Puri Bhaji',
    description: 'Fried bread with potato curry',
    price: 50,
    image: 'https://images.unsplash.com/photo-1601050690117-03f1eb2b6f3a?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
  },
  {
    id: 'bc1',
    name: 'Breakfast Combo',
    description: '2 Idli + 1 Vada + Sambar + Chutney + Coffee',
    price: 60,
    originalPrice: 80,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=400&fit=crop',
    category: 'breakfast',
    isVeg: true,
    available: true,
    isCombo: true,
  },
  
  // Lunch
  {
    id: 'l1',
    name: 'Veg Meals',
    description: 'Rice, sambar, rasam, 2 vegetables, curd, papad',
    price: 80,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: true,
    available: true,
  },
  {
    id: 'l2',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice with spiced chicken',
    price: 120,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: false,
    available: true,
    customizations: ['Extra Raita', 'Extra Gravy'],
  },
  {
    id: 'l3',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry with fried bread',
    price: 70,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: true,
    available: true,
  },
  {
    id: 'l4',
    name: 'Paneer Butter Masala with Roti',
    description: 'Rich paneer curry with 3 rotis',
    price: 90,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: true,
    available: true,
  },
  {
    id: 'l5',
    name: 'Fish Fry Meals',
    description: 'Rice with fish fry and gravy',
    price: 130,
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: false,
    available: false,
  },
  {
    id: 'l6',
    name: 'Rajma Chawal',
    description: 'Red kidney beans curry with steamed rice',
    price: 75,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: true,
    available: true,
  },
  {
    id: 'l7',
    name: 'Egg Curry Meals',
    description: 'Boiled eggs in spicy gravy with rice',
    price: 85,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: false,
    available: true,
  },
  {
    id: 'lc1',
    name: 'Lunch Special Combo',
    description: 'Biryani + Raita + Salad + Gulab Jamun',
    price: 140,
    originalPrice: 170,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=400&fit=crop',
    category: 'lunch',
    isVeg: false,
    available: true,
    isCombo: true,
  },

  // Snacks
  {
    id: 's1',
    name: 'Samosa',
    description: 'Crispy fried pastry with spiced filling',
    price: 20,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's2',
    name: 'Pav Bhaji',
    description: 'Spiced mashed vegetables with bread',
    price: 60,
    image: 'https://images.unsplash.com/photo-1606491956639-c6df6d69a1cc?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's3',
    name: 'Veg Sandwich',
    description: 'Grilled sandwich with vegetables',
    price: 40,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    customizations: ['Extra Cheese', 'Grilled'],
  },
  {
    id: 's4',
    name: 'Masala Chai',
    description: 'Hot spiced milk tea',
    price: 15,
    image: 'https://images.unsplash.com/photo-1597318130226-091b6fa7e44a?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's5',
    name: 'Coffee',
    description: 'Fresh filter coffee',
    price: 20,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's6',
    name: 'Pakora',
    description: 'Mixed vegetable fritters',
    price: 30,
    image: 'https://images.unsplash.com/photo-1606850780554-b55fb4dd4b48?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's7',
    name: 'Mango Milkshake',
    description: 'Creamy mango shake with ice cream',
    price: 50,
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    customizations: ['Extra Thick', 'Less Sugar'],
  },
  {
    id: 's8',
    name: 'Chocolate Milkshake',
    description: 'Rich chocolate shake with whipped cream',
    price: 55,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    customizations: ['Extra Thick', 'Less Sugar'],
  },
  {
    id: 's9',
    name: 'Strawberry Milkshake',
    description: 'Fresh strawberry shake with ice cream',
    price: 55,
    image: 'https://images.unsplash.com/photo-1589739900243-c4e0e6b11d8b?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    customizations: ['Extra Thick', 'Less Sugar'],
  },
  {
    id: 's10',
    name: 'Banana Milkshake',
    description: 'Creamy banana shake with honey',
    price: 45,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    customizations: ['Extra Thick', 'Less Sugar'],
  },
  {
    id: 's11',
    name: 'Vada Pav',
    description: 'Spiced potato fritter in bread bun',
    price: 25,
    image: 'https://images.unsplash.com/photo-1606491956391-ba0629958edc?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 's12',
    name: 'Bhel Puri',
    description: 'Tangy puffed rice snack mix',
    price: 35,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
  },
  {
    id: 'sc1',
    name: 'Snack Combo',
    description: '2 Samosas + Chai + Pakora',
    price: 55,
    originalPrice: 75,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    isCombo: true,
  },
  {
    id: 'sc2',
    name: 'Shake Combo',
    description: 'Any Milkshake + Veg Sandwich',
    price: 80,
    originalPrice: 95,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&h=400&fit=crop',
    category: 'snacks',
    isVeg: true,
    available: true,
    isCombo: true,
  },

  // Dinner
  {
    id: 'd1',
    name: 'Dal Tadka with Roti',
    description: 'Tempered lentils with 3 rotis',
    price: 70,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
  },
  {
    id: 'd2',
    name: 'Chicken Curry with Rice',
    description: 'Spicy chicken curry with steamed rice',
    price: 110,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: false,
    available: true,
  },
  {
    id: 'd3',
    name: 'Veg Fried Rice',
    description: 'Stir-fried rice with mixed vegetables',
    price: 80,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
  },
  {
    id: 'd4',
    name: 'Chapati with Veg Kurma',
    description: '4 chapatis with vegetable kurma',
    price: 75,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
  },
  {
    id: 'd5',
    name: 'Mutton Biryani',
    description: 'Aromatic rice with tender mutton',
    price: 150,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: false,
    available: true,
  },
  {
    id: 'd6',
    name: 'Palak Paneer with Naan',
    description: 'Spinach and cottage cheese curry with naan',
    price: 95,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
  },
  {
    id: 'd7',
    name: 'Fried Rice with Manchurian',
    description: 'Veg fried rice with veg manchurian gravy',
    price: 90,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
  },
  {
    id: 'd8',
    name: 'Chicken Fried Rice',
    description: 'Indo-Chinese fried rice with chicken',
    price: 100,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: false,
    available: true,
  },
  {
    id: 'dc1',
    name: 'Dinner Special',
    description: '3 Roti + Dal + Veg + Rice + Sweet',
    price: 100,
    originalPrice: 130,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=400&fit=crop',
    category: 'dinner',
    isVeg: true,
    available: true,
    isCombo: true,
  },
];